### ISSUE TITLE
请问下64位系统下是否移去了dbg-asm等脚本？

### ISSUE THREAD

**Issue by Wangzhike** [DeathKing/hit-oslab#8]
我在ubuntu 14.04 LTS 64位的机子上，执行配置，系统可以正常启动，但oslab目录下，没有发现32位下提到的诸如dbg-asm、dbg-c、rungdb等脚本，是否可以在对32位的脚本进行修改，移植到64位？

**Comment by DeathKing** [comment]
@Wangzhike 原生工具是32位的。没有打算移植到64位。考虑到这个主要是用来学习，而非开发的。配置一个 32 位的Ubuntu虚拟机应该没那么麻烦。
